 //
 // Tokenzier.swift 
 //
 // Copyright (c) 2017 Qiang, Guo <mcknight0219@gmail.com>
 // Author: Qiang, Guo <mcknight0219@gmail.com>
 //
 // Permission is hereby granted, free of charge, to any person obtaining a copy of
 // this software and associated documentation files (the "Software"), to deal in
 // the Software without restriction, including without limitation the rights to
 // use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 // the Software, and to permit persons to whom the Software is furnished to do so,
 // subject to the following conditions:
 //
 // The above copyright notice and this permission notice shall be included in all
 // copies or substantial portions of the Software.
 //
 // THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 // IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 // FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 // COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 // IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 // CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 //

import Foundation

/// Possible tokens generated by tokenizer
public enum Token {
	case word(String)
	// Number is important in list
	case number(Int)
	// Non-alphanum characters
	case marker(String)
	// tabs, whitespaces, and etc.
	case whitespace(String)
	// important so not included in .whitespace
	case newline
}

public struct Tokenizer {	

	/// the target to be tokenzied
	let text: String!

	/// the current index
	var cur: String.Index
	
	/// Initialize a tokenizer
	///
	/// - Parameters:
	///		= text: the target string
	///		= range: specify range of text to be processed
	///
	public init(_ text: String, range: Range<String.Index>? = nil) {
		guard range != nil else {
			self.text = text
			self.cur = self.text.startIndex
			return
		}

		let r = range!
		self.text = text.substring(with: r)
		self.cur = self.text.startIndex
	}
	
    /// Return the next token
    ///
	public mutating func next() -> Token? {
		guard hasNext() else {
			return nil
		}

		return glob()
	}

    /// If tokenizer has reached the end
    ///
	public func hasNext() -> Bool {
		return self.cur < self.text.endIndex
	}

    /// Reset the cur to starIndex
	public mutating func rewind() -> Void {
        self.cur = self.text.startIndex
	}


    // MARK: Implementation
    
	/// Return character under current cursor
    /// Note: Alwasy assume index is within range.
	func currentCharacter() -> String {
		return String(self.text[self.cur])
	}

	/// Get next token
	mutating func glob() -> Token {
		let c = currentCharacter()

		if c.isWs() {
			let start = cur
			while hasNext() && currentCharacter().isWs() {
				cur = self.text.index(after: cur)
			}
            return .whitespace(self.text.substring(from: start, to: cur)!)
		}
        
        
        if c == "\n" {
            // glob as many new line as possible
            
        }
        
        return .newline
	}

}
